### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by JoanaDalmeida** [klee-contrib/focus-demo-app#120]
Étapes pour reproduire le bug :
1. \- Sur la fiche d'un film, section "Casting", cliquer sur le bouton "Prévisualiser" 
2. \- Ensuite cliquer sur  le bouton 'Consulter la fiche"

On a une erreur : Uncaught TypeError: Cannot read property 'firstChild' of undefined

**Comment by TomGallon** [comment]
J'ai toujours le probleme.

![image](https://cloud.githubusercontent.com/assets/5349745/14487108/02cc6068-0161-11e6-817e-c5f4d32979a2.png)

**Comment by JoanaDalmeida** [comment]
La PR n'est pas encore mergée :)
