### ISSUE TITLE
Recherche incohérente

### ISSUE THREAD

**Issue by TomGallon** [klee-contrib/focus-demo-app#127]
Dans la recherche (rapide), je tape "sta" je n'ai aucun résultats, je tape "stars" j'ai des résultats.
Je cherche même "st" j'ai des résultats.

Pourquoi ce comportement de l'api ?

**Comment by Bernardstanislas** [comment]
:gb: ?
Ca ne sera pas possible dans la version actuelle du backend node, donc soit nouveau backend, soit Vertigo........ :blush:
