### ISSUE TITLE
Problème avec la mise en place de réac router

### ISSUE THREAD

**Issue by TomGallon** [klee-contrib/focus-demo-app#164]
- [x] il reste des `navigate`qui génèrent une erreur et qui bloquent la navigation. a corriger.
  <img width="927" alt="capture d ecran 2016-06-09 a 23 11 24" src="https://cloud.githubusercontent.com/assets/5349745/15946557/a3ddd65e-2e97-11e6-9922-787607548cc1.png">
- [x] on a perdu le retour en haut de page lors de la navigation
- [x] quand je navigue, j’arrive a avoir une url de ce type :http://localhost:3000/movies/persons/102631
  (pour y arriver je suis passé d’un movie à une person). j’ai l’impression que l’url se rafraichit mal. si je raffraichit ma page, ca plante...

**Comment by TomGallon** [comment]
@pierr j'ai créé l'issue.

**Comment by pierr** [comment]
Il faut faire les mêmes tests sur la branche Backbone

**Comment by pierr** [comment]
Et faire les tests avec F5 et soit le createHashHistory spit en modifiable or webpack Dev server pour Qu'il serve toutes les routes sous /\* avec index.html
